
service: exampleService

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  cfLogs: true
  timeout: 50
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:*
        - cloudwatch:*
        - events:*
      Resource: "*"

functions:
  main:
    handler: main.main

resources:
  Resources:
    MainLogGroup:
      Properties:
        RetentionInDays: "14"
